variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - analysis
  - build
  - test
  - coverage
  - deploy

before_script:
  - hostname
  - whoami
# - pwd

analysis-headers:
  image: ubuntu:20.04
  stage: analysis
  artifacts:
    name: analysis-headers
    when: always
    paths:
      - streampu.hpp
  tags:
    - x86_64
    - linux
    - docker
  script:
    - ./scripts/generate_streampu_header.sh streampu.hpp
    - diff streampu.hpp include/streampu.hpp

analysis-clang-format:
  image: ubuntu:22.04
  stage: analysis
  tags:
    - x86_64
    - linux
    - docker
  script:
    - apt-get update
    - apt-get -y install clang-format
    - mkdir original_code
    - cp -r include original_code
    - cp -r src original_code
    - cp -r tests original_code
    - cp -r signal_tracer original_code
    - ./scripts/apply_clang_format.sh
    - mkdir new_code
    - cp -r include new_code
    - cp -r src new_code
    - cp -r tests new_code
    - cp -r signal_tracer new_code
    - diff -r new_code original_code

build-linux-gcc-x64-avx2:
  image: registry.gitlab.com/aff3ct/aff3ct/x86_64_ubuntu_gcc:v9.3.0
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  except:
    - schedules
  needs:
    - job: analysis-headers
      artifacts: false
  tags:
    - x86_64
    - linux
    - docker
  artifacts:
    name: build-linux-gcc-x64-avx2
    paths:
      - build_linux_gcc_x64_avx2
  script:
    - export CXX="g++"
    - export CFLAGS="-Wall -funroll-loops -m64 -mavx2 -mfma"
    - export LFLAGS="-static -static-libgcc -static-libstdc++ -Wl,--whole-archive -lrt -lpthread -Wl,--no-whole-archive"
    - export GIT_TAG="v0.0.0"
    - export CMAKE_OPT="-DSPU_TESTS=ON -DSPU_COMPILE_STATIC_LIB=ON -DSPU_COMPILE_SHARED_LIB=ON -DSPU_STACKTRACE=OFF -DSPU_OVERRIDE_VERSION=$GIT_TAG"
    - export NAME="build_linux_gcc_x64_avx2"
    - source ./ci/tools/threads.sh
    - ./ci/build-linux-macos.sh

build-linux-gcc-coverage-regression:
  image: registry.gitlab.com/aff3ct/aff3ct/x86_64_ubuntu_coverage
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  needs:
    - job: analysis-headers
      artifacts: false
  tags:
    - x86_64
    - linux
    - docker
  artifacts:
    name: regression-code-coverage-files
    when: always
    paths:
      - build/
      - code_coverage_files/
  script:
    - export CXX="g++"
    - export CFLAGS="-Wall -funroll-loops -msse4.2 --coverage"
    - export LFLAGS="--coverage"
    - export GIT_TAG="v0.0.0"
    - export CMAKE_OPT="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG=-O0 -DSPU_TESTS=ON -DSPU_COMPILE_STATIC_LIB=ON -DSPU_COMPILE_SHARED_LIB=ON -DSPU_LINK_HWLOC=ON -DSPU_OVERRIDE_VERSION=$GIT_TAG"
    - source ./ci/tools/threads.sh
    - ./ci/build-linux-macos.sh
    - ./ci/test-coverage-regression.sh
    - rm -rf build/bin
    - rm -rf build/lib

build-linux-clang:
  image: registry.gitlab.com/aff3ct/aff3ct/x86_64_ubuntu_clang:v10.0.0
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  except:
    - schedules
  needs:
    - job: analysis-headers
      artifacts: false
  tags:
    - x86_64
    - linux
    - docker
  artifacts:
    name: build-linux-clang
    paths:
      - build_linux_clang
  script:
    - export CXX="clang++"
    - export CFLAGS="-Wall -Wno-overloaded-virtual -funroll-loops"
    - export GIT_TAG="v0.0.0"
    - export CMAKE_OPT="-DSPU_TESTS=ON -DSPU_COMPILE_STATIC_LIB=ON -DSPU_COMPILE_SHARED_LIB=ON -DSPU_OVERRIDE_VERSION=$GIT_TAG"
    - export NAME="build_linux_clang"
    - source ./ci/tools/threads.sh
    - ./ci/build-linux-macos.sh

build-linux-icpc:
  image: intel/oneapi-hpckit:2022.2-devel-ubuntu20.04
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  except:
    - schedules
  needs:
    - job: analysis-headers
      artifacts: false
  tags:
    - x86_64
    - linux
    - docker
  artifacts:
    name: build-linux-icpc
    paths:
      - build_linux_icpc
  script:
    - export CXX="icpc"
    - export CFLAGS="-Wall -funroll-loops -march=native -std=c++11"
    - export GIT_TAG="v0.0.0"
    - export CMAKE_OPT="-DSPU_TESTS=ON -DSPU_COMPILE_STATIC_LIB=ON -DSPU_COMPILE_SHARED_LIB=ON -DSPU_OVERRIDE_VERSION=$GIT_TAG"
    - export NAME="build_linux_icpc"
    - source ./ci/tools/threads.sh
    - ./ci/build-linux-macos.sh

test-memcheck-regression:
  image: registry.gitlab.com/aff3ct/aff3ct/x86_64_ubuntu_valgrind
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  except:
    - schedules
  needs:
    - job: analysis-headers
      artifacts: false
  tags:
    - x86_64
    - avx2
    - linux
    - docker
  artifacts:
    name: test-memcheck-regression
    when: always
    paths:
      - build/Testing
  script:
    - export CXX="g++"
    - export CFLAGS="-Wall -funroll-loops -m64 -mavx2 -mfma"
    - export GIT_TAG="v0.0.0"
    - export CMAKE_OPT="-DCMAKE_BUILD_TYPE=RelWithDebInfo -DSPU_TESTS=ON -DSPU_COMPILE_STATIC_LIB=ON -DSPU_COMPILE_SHARED_LIB=ON -DSPU_LINK_HWLOC=ON -DSPU_OVERRIDE_VERSION=$GIT_TAG"
    - source ./ci/tools/threads.sh
    - ./ci/build-linux-macos.sh
    - ./ci/test-memcheck-regression.sh

coverage-linux:
  image: registry.gitlab.com/aff3ct/aff3ct/x86_64_ubuntu_coverage
  stage: coverage
  except:
    - schedules
  needs:
    - job: build-linux-gcc-coverage-regression
      artifacts: true
  tags:
    - x86_64
    - linux
    - docker
  coverage: '/.*lines\.*: (\d+.\d+\%)/'
  artifacts:
     name: code-coverage-report
     when: always
     paths:
       - code_coverage_report/
  script:
    - ./ci/coverage-linux.sh

pages:
  stage: deploy
  except:
    - schedules
  tags:
    - linux
  dependencies:
    - coverage-linux
  allow_failure: true
  script:
    - mv code_coverage_report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - develop
